config/routes.rb
Myunischedule::Application.routes.draw do
  
  get "o_auth/logout"
  get "o_auth/login"
  get "o_auth/choose"
  
  get "reports/csvusers"
  get "reports/csvcourses"

  resources :schedules
  
  root :to => 'schedules#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :courses
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  require 'rubygems'
  require 'icalendar'
  require 'open-uri'
  include Icalendar
  
  def is_logged_in_fb?
    
    redirect_to :action => 'index' if !session[:access_token] || !session[:user_id] || !User.exists?(:id => session[:user_id])
    
  end
  
  # GET /schedules
  # GET /schedules.xml
  def index
    
    if logged_in_fb?
      
      #facebook graph
      @graph = current_graph
      @user = @graph.get_object('me')
      
      #current_user's schedule
      @schedule = current_user.schedule
      
      if @schedule
        @colors = ["#FF0000", "#162EAE", "#00AF64", "#CE0071", "#7309AA", "#FF4F00", "#323086", "#CE0071", "#250672", "#000000", "#000000", 
          "#000000", "#000000", "#000000"]
        @textColors = ["#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", "#FFFFF", 
          "#FFFFF", "#FFFFF", "#FFFFF"]
        @weekds = {"0" => 7, "1" => 8, "2" => 9, "3" => 10, "4" => 11, "5" => 12, "6" => 13}
        @students = Hash.new
        @courses = @schedule.courses
        @courses.each do |c|
          tsch = Course.find_by_id(c.id).schedules
          @students[c.name] = []
          tsch.each do |u|
            @students[c.name] << u.user if u.user.id != session[:user_id]
          end
        
        end
      end
      
    else
      
      @oauth = Koala::Facebook::OAuth.new("#{ENV['SITE'] ? ENV['SITE'] : 'http://localhost:3000'}/o_auth/login")
      
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    is_logged_in_fb?
    @schedule = Schedule.find(params[:id])
    
    if @schedule.user.id == session[:user_id]
    
      @courses = @schedule.courses
      
    else
      
      flash[:error] = "This schedule is not yours!"
      
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    is_logged_in_fb?
    
    if User.find(session[:user_id]).schedule
      
      redirect_to root_path
      
    else
    
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
    end
  end

  # GET /schedules/1/edit
  def edit
    is_logged_in_fb?
    #@schedule = Schedule.find(params[:id])
    redirect_to root_path
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    is_logged_in_fb?
    success = true
    
    if params[:schedule][:vcal]
      
      if current_user.parseCalendar(params[:schedule][:vcal].tempfile)
        
        success = true
        
      else
        
        success = false
        flash[:error] = "Invalid file!"
        
      end
      
    elsif params[:schedule][:callink]
      
      theLink = params[:schedule][:callink].include?(".ical") ? params[:schedule][:callink] : params[:schedule][:callink] + ".ics"
      
      if current_user.parseCalendar(open(theLink))
        
        success = true
        
      else
        
        success = false
        flash[:error] = "Invalid file!"
        
      end
      
    end

    respond_to do |format|
      if success 
        format.html { redirect_to(root_path, :notice => 'Schedule was successfully created.') }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { redirect_to root_path }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    is_logged_in_fb?
    redirect_to root_path
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    is_logged_in_fb?
    @schedule = Schedule.find(params[:id])
    if @schedule.user.id == session[:user_id]
      @schedule.destroy
    else
      
      flash[:error] = "That's not your schedule silly!"
      
    end

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<% if current_user.school.has_upload %>
<%= form_tag '/schedules', :multipart => true do %>
	<div id="error"><%= flash[:error] %> </div>
  <div class="field">
    iCal File:<br />
    <%= file_field :schedule, :vcal  %>
	<% if current_user.school.has_link_upload %>
	<p style="align:center">-OR-</p>
	<%= text_field :schedule, :callink, :placeholder => "Paste iCal link here" %>
	<% end %>
  </div>
  <div class="actions">
    <%= submit_tag 'Submit' %>
  </div>
<% end %>
<% end %>

app/views/schedules/_intro1.html.erb
You are ready to upload your schedule! <ol style="width:50%;margin: 0 auto;"> <li>Go to SIO</li><li>Go to "Course Schedule"</li><li>Click "Semester Schedule"</li><span style="color:red">(MAKE SURE YOU USE THE "SEMESTER SCHEDULE" NOT THE "PLAN COURSE SCHEDULE" ! If you make this mistake, simply delete your schedule on this site and re-upload.)</span><li>Click "Calendar Export"</li><li>Upload this file (.ics) by clicking "Browse" below</li><li>You will be able to see who else is in your classes!</li></ol>

app/views/schedules/_intro2.html.erb
You are ready to upload your schedule! <ol style="width:50%;margin: 0 auto;"> <li>Go to Penn In Touch and login</li><li>Make sure you choose the right semester.</li><li>Click "Export as iCalendar" under your schedule.</li><li>Upload this file (.ics) by clicking "Browse" below</li><li>You will be able to see who else is in your classes!</li></ol>

app/views/schedules/_introCarnegieMellonUniversity.html.erb
You are ready to upload your schedule! <br> <br> <strong>Copy your ScheduleMan link into the iCal link box.</strong> <br> -OR- </br> <ol style="width:50%;margin: 0 auto;"> <li>Go to SIO</li><li>Go to "Course Schedule"</li><li>Click "Semester Schedule"</li><li>Click "Calendar Export"</li><li>Upload this file (.ics) by clicking "Browse" below</li><li>You will be able to see who else is in your classes!</li></ol>

app/views/schedules/_introUniversityOfPennsylvania.html.erb
You are ready to upload your schedule! <ol style="width:50%;margin: 0 auto;"> <li>Go to Penn In Touch and login</li><li>Make sure you choose the right semester.</li><li>Click "Export as iCalendar" under your schedule.</li><li>Upload this file (.ics) by clicking "Browse" below</li><li>You will be able to see who else is in your classes!</li></ol>

app/views/schedules/_introUniversityofPennsylvania.html.erb
You are ready to upload your schedule! <ol style="width:50%;margin: 0 auto;"> <li>Go to Penn In Touch and login</li><li>Make sure you choose the right semester.</li><li>Click "Export as iCalendar" under your schedule.</li><li>Upload this file (.ics) by clicking "Browse" below</li><li>You will be able to see who else is in your classes!</li></ol>

app/views/schedules/_jschedule.js.erb
<% zone = ActiveSupport::TimeZone.new("Eastern Time (US & Canada)") %>
$(document).ready(function() {
	
	$('#calendar').fullCalendar({
		header: false,
		year: 2011,
		month: 7,
		date: 7,
		events: [
		<% i = 0 %>
		<% minTime = 24 %>
		<% maxTime = 0 %>
		<% kends = "false" %>
		<% @courses.each do |c|%>
			<% minTime = c.start.hour-1 if c.start.hour < minTime %>
			<% maxTime = c.end.hour+2 if c.end.hour > maxTime %>
			<% c.weekdays.delete("[").delete("]").delete('"').delete(" ").split(",").each do |w| %>
			<% kends = "true" if w == 0 || w == 7 %>
			{
				title: '<%= c.name %>',
				start: new Date(2011, 7, <%= @weekds[w] %>, <%= c.start.hour %>, <%= c.start.min %>),
				end: new Date(2011, 7, <%= @weekds[w] %>, <%= c.end.hour %>, <%= c.end.min %>),
				allDay: false,
				className: 'calevent1',
				color: '<%= @colors[i] ? @colors[i] : "#00000" %>',
				textColor: '<%= @textColors[i] ? @textColors[i] : "#FFFFF" %>'
			},
			<% end %>
			<% i+=1 %>
		<% end %>
		], minTime: '<%= minTime %>:00',maxTime: '<%= maxTime %>:00', weekends: <%= kends %>, disableDragging: true, disableResizing: true
	}).fullCalendar('changeView', 'agendaWeek');
	
	//ACCORDION BUTTON ACTION (ON CLICK DO THE FOLLOWING)
	$('.accordionButton').click(function() {

		//REMOVE THE ON CLASS FROM ALL BUTTONS
		$('.accordionButton').removeClass('on');
		  
		//NO MATTER WHAT WE CLOSE ALL OPEN SLIDES
	 	$('.accordionContent').slideUp('normal');
   
		//IF THE NEXT SLIDE WASN'T OPEN THEN OPEN IT
		if($(this).next().is(':hidden') == true) {
			
			//ADD THE ON CLASS TO THE BUTTON
			$(this).addClass('on');
			  
			//OPEN THE SLIDE
			$(this).next().slideDown('normal');
		 } 
		  
	 });
	  
	
	/*** REMOVE IF MOUSEOVER IS NOT REQUIRED ***/
	
	//ADDS THE .OVER CLASS FROM THE STYLESHEET ON MOUSEOVER 
	$('.accordionButton').mouseover(function() {
		$(this).addClass('over');
		
	//ON MOUSEOUT REMOVE THE OVER CLASS
	}).mouseout(function() {
		$(this).removeClass('over');										
	});
	
	/*** END REMOVE IF MOUSEOVER IS NOT REQUIRED ***/
	
	
	/********************************************************************************************************************
	CLOSES ALL S ON PAGE LOAD
	********************************************************************************************************************/	
	$('.accordionContent').hide();
});

app/views/schedules/_topbar.html.erb
<div id="topbar">
	
	<% if !@user %>
	<div id="login"><%= link_to image_tag('myulogo.png'), root_path %></div><div id="login-l">Login via <%= link_to image_tag('fbbutton.gif'), @oauth.url_for_oauth_code(:permissions => 'user_education_history') %></div>
	<% else %>
	<div id="login"><%= link_to image_tag('myulogo.png'), root_path %></div>
	<div id="user">School: <%= current_user.school.name %> | <%= @user["name"] %>
	<%= image_tag @graph.get_picture('me',{:type => 'small'}) %><%= link_to 'Logout', {:controller => 'o_auth', :action => 'logout'}, :id => 'logout' %></div>
	<% end %>
	
</div>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<% if @schools %>
<ol style="width:50%;margin: 0 auto;">
	<% @schools.each do |s| %>
	
		<li><%= s.name %></li>
	
	<% end %>
</ol>
<% end %>

<% if @courses %>
	<div id="maintext">Below is your schedule of classes with the names and facebook links to all of the students in those classes that have uploaded their schedules. Once more students in your classes upload their schedules, they will appear on this page. Make sure to check back every once in a while for new additions!<% if current_user.school.name == "University of Pennsylvania" %><span style="color:green">If you're schedule is weird in any way, please re-upload and email me if it persists (hmind2005@gmail.com).</span><% end %></div></br>
	</br>
	<div id="schedulewrap">
	<div id='calendar'><div id="schops">
	    <td><%= link_to 'Delete my Schedule', @schedule, :confirm => 'Are you sure?', :method => :delete %></td>
	</div></div>
	<div id="accordion">
		<% e = 0 %>
		<% @courses.each do |c|%>
	    <div class="accordionButton" style="background-color:<%= @colors[e] ? @colors[e] : "#000000" %>;color:<%= @textColors[e] ? @textColors[e] : "#FFFFFF" %>;"><%= c.name %></div>
		<div class="accordionContent" style="background-color:<%= @colors[e] ? @colors[e] : "#000000" %>">
			<table style="margin:0 auto;text-align:center;">
				<% @students[c.name].each do |s| %>
				<tr>
					<td>
					<img src="http://graph.facebook.com/<%= s.fbid %>/picture" style="height:40px;width:40px;float:left;">
					<a href="<%= s.link %>" target="_blank" style="color:white;float:right;margin-top:10px;"><%= s.name %></a>
					</td>
				</tr>
				<% end %>
				<% if @students[c.name].count < 1%>
					<tr>
						<td>
							No one from this section has added their schedules =( Check back later!
						</td>
					</tr>
				<% end %>
			</table>
		</div>
		<% e+=1 %>
		<% end %>
	</div>
	</div>
<% else %>
<% if @user %>
<div id="maintext"><%= render :partial => "intro#{current_user.school.name.delete(' ')}" %></div>
</br>
<div id='upform'>
<%= render 'form' %>
</div>
<% else %>

<div id="maintext">Welcome to myUniSchedule! This site allows students to upload their class schedules and link with others that are in their classes! Click the facebook button above to login with your facebook. You must have a supported school in your facebook education profile. If you have any errors or gltiches (or suggestions), email me at hmind2005@gmail.com or follow me on twitter below.</div>
</br>
<%= link_to image_tag('introim.png'), @oauth.url_for_oauth_code(:permissions => 'user_education_history'), :style=> "margin-left:auto;margin-right:auto;" %>
<% end %>
<% end %>
</div>

app/views/schedules/new.html.erb
<div id="content">
<div id="uni-error"><%= flash[:error] %></div>
<div id="uni-form">
<h1>Upload Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>
</div>
</div>

app/views/schedules/show.html.erb
<div id="content">
<p id="uni-success"><%= flash[:notice] %></p>

<% if @courses %>
<table>
	<tr>
		<th>Course</th>
		<th>Days</th>
	</tr>
	<% @courses.each do |c| %>
	<tr>
		<td><%= c.name %></td>
		<td><%= c.weekdays %></td>
	</tr>
	<% end %>
</table>

<% end %>

<%= link_to 'Continue >', root_path %>
</div>